### ISSUE TITLE
Temprory block nightly users install this theme

### ISSUE THREAD

**Issue by lychichem** [louischan/simplewhite#32] opened 2015-04-02 02:48 UTC
On firefox nightly 40.0a1(20150401)， your theme meets severe problem that brock the chrome of nightly. If you don't want to fix, please block nightly users from install your theme.

**Comment by louischan** [comment] 2015-04-02 04:09
Just lowered max supported version in addons.mozilla.org. I'm looking into the issue.

**Comment by louischan** [comment] 2015-04-02 05:12
Before, the default theme for Windows had two separate themes internally. One was called **classic** (for Windows XP), the other was called **aero** (for Windows Vista or later). Simple White is based on aero theme.

In the latest Nightly, they wanted to reduce the number of duplicated files, so they merged two themes together. Files that were unique to Windows Vista or later are added `-aero` suffix in their filenames. To name a few:
```global/menu-aero.css
global/notification-aero.css
global/popup-aero.css
browser/browser-aero.css
browser/identity-aero.png
browser/downloads/downloads-aero.css
(and many more)
```
When `chrome://browser/skin/browser.css` is accessed in Windows Vista or later, `browser/browser-aero.css` is served instead of `browser/browser.css`. And I don't know how to override this behaviour.

This happened to some files before (like `browser/Toolbar.png`), but now it happens in a much bigger scale. To the default theme, this means less duplicated files. To custom themes, this means more duplicated files since many assets are the same for WinXP, Vista+ as well as other platforms (for example, `browser/Toolbar.png` and `browser/Toolbar-aero.png` are identical).

More discussion about this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1150006

**Comment by lychichem** [comment] 2015-04-02 13:05
Well, sadly to see the bug on bugzilla... Will it be difficult to release two build, one for xp+ and another for xp?

**Comment by louischan** [comment] 2015-04-03 04:58
[1150006#c24](https://bugzilla.mozilla.org/show_bug.cgi?id=1150006#c24) mentioned they will make those overrides only be loaded for the default theme. I will wait to see how it goes.

Btw, here's another bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1150417

**Comment by lychichem** [comment] 2015-04-03 07:54
As the last commet on bug 1150006 says, the problem have been fixed and maybe theme will be okey after tonight's update of nightly.

**Comment by lychichem** [comment] 2015-04-06 04:37
Now you can make nightly users install your version. Mozilla fixed the bug.

**Comment by louischan** [comment] 2015-04-06 08:13
Confirmed. Reverted max supported version of v2.2b16 to Firefox 40.

**Closed by louischan** 2015-04-06 08:13 UTC

**Comment by lychichem** [comment] 2015-04-07 12:24
But still minor bugs:1. Realtime bookmark folder's icon can't be shown. 2.Icon of "extensions" and "themes" in about:addon is not the value writen in CSS.
